name: Spec

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        cd nextapp
        npm install
        npm run spec

    - name: Check prettier
      run: |
        cd nextapp
        npm run pretty-check

    - name: Check ESLint
      run: |
        cd nextapp
        npm run lint

    - name: Run nextapp unit tests
      run: |
        cd nextapp
        npm run spec
